DATA:
  IMAGE_SIZE: 256
  IN_CHANS: 1 
  NUM_CLASSES: 4
  CLASS_FREQ: [0.5011806339025498, 0.2339875698089599, 0.1408609151840210, 0.1239708922803402]
  MEAN: 0.28328466976390165
  STD: 0.12623453327253753
MODEL:
  ENCODER:
    USE_MULTI_MERGE: True
    USE_GHOST_FFN: True
  DECODER:
    EMBED_DIM: 24
    FUSE_OP: 'cat'
TRAIN:
  EPOCHS: 200
  WARMUP_EPOCHS: 3
  LR: 6e-5
  CRF_FREQUNCY: 20
  CRF_START_EPOCH: 10
  CRF_STOP_EPOCH: 150
